---
title: "HelloWorld"
output: html_document
---
 "I'm Learning to Use Github...Boom"

```{r}
library(ggplot2)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

```{r}
library(tidyverse)
beaches <- read_csv("./beaches.csv")

cereal <- read_csv("./cereal.csv")

weather <- read_csv("./weather.csv")
```

```{r}
ggplot(data = cereal, aes(cereal$sugars, cereal$rating)) + geom_point()

hist(beaches$temperature)

ggplot(data = cereal, aes(cereal$protein, cereal$rating)) + geom_point() + geom_smooth(aes(x = cereal$protein, y = cereal$rating))

```
```{r}
ggplot(
  data = beaches,
  mapping = aes(
    x = temperature, 
    y = rainfall
  ) 
) + 
geom_point(
  mapping = aes(colour = season_name), 
  size = 2
) + 
geom_rug() + 
facet_wrap(vars(season_name))
```
```{r}
ggplot(data = cereal) +
  aes(x = mfr, y = as.integer(sugars)) +
  geom_bar(stat = "identity", alpha = 0.8) +
  labs(title = "Sugars per Manufacturer",
       y = "Average Sugars",
       x = "Manufacturer") +
  theme_minimal()

```


